# Generated by Django 4.2.7 on 2025-08-08 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('cor_primaria', models.CharField(default='#007bff', help_text='Formato: #RRGGBB', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#6c757d', help_text='Formato: #RRGGBB', max_length=7, verbose_name='Cor Secundária')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('apresentacao', models.TextField(help_text='Breve apresentação pessoal', verbose_name='Apresentação')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pessoas/', verbose_name='Foto de Perfil')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('linktree_url', models.URLField(blank=True, verbose_name='Linktree')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='nfc_cards.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_empresa_owner', models.BooleanField(default=False, verbose_name='É proprietário da empresa')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='nfc_cards.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Pet')),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('peixe', 'Peixe'), ('outro', 'Outro')], max_length=20, verbose_name='Espécie')),
                ('raca', models.CharField(blank=True, max_length=50, verbose_name='Raça')),
                ('porte', models.CharField(blank=True, choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=20, verbose_name='Porte')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Foto do Pet')),
                ('veterinario', models.CharField(blank=True, max_length=100, verbose_name='Veterinário')),
                ('telefone_veterinario', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Veterinário')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Especiais')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='nfc_cards.empresa', verbose_name='Empresa')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='nfc_cards.person', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_nfc', models.CharField(max_length=50, unique=True, verbose_name='Código NFC')),
                ('tipo', models.CharField(choices=[('pessoa', 'Cartão de Visita'), ('pet', 'Carteirinha de Pet')], max_length=20, verbose_name='Tipo de Cartão')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_nfc', to='nfc_cards.empresa', verbose_name='Empresa')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_nfc', to='nfc_cards.person')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_nfc', to='nfc_cards.pet')),
            ],
            options={
                'verbose_name': 'Cartão NFC',
                'verbose_name_plural': 'Cartões NFC',
                'ordering': ['-criado_em'],
            },
        ),
    ]
